version: '3'
services:
  myapp:
    build:
      context: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./storage:/app/storage
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml