[tool.poetry]
name = "my-web"
version = "0.1.0"
description = ""
authors = ["Sinazija <sinazija987@gmail.com>"]
readme = "README.md"
packages = [{include = "my_web"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
